[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Environment variables for Neon database
# Set VITE_DATABASE_URL in Netlify dashboard under Site Settings > Environment Variables